name: Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Doxygen
        run: sudo apt-get install doxygen

      - name: Generate Doxygen documentation
        run: doxygen ./Doxyfile

      - name: Commit and push documentation
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add ./docs/  # Change this path to match your Doxygen output directory
          git commit -m "Update Doxygen documentation" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}